name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15, windows-2019 ]
        ghc: [ '8.10' ]
        cabal: [ '3.2' ]
        include:
          - { os: ubuntu-18.04, ghc: '8.8', cabal: '3.2' }
          - { os: ubuntu-18.04, ghc: '8.6', cabal: '3.2' }
          - { os: ubuntu-18.04, ghc: '8.4', cabal: '3.2' }
    name: ${{ matrix.os }} ghc-${{ matrix.ghc }} cabal-${{ matrix.cabal }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-
            ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build
      - run: cabal test --test-show-details direct
      - run: cabal exec -- sh -c 'cp -v "$( which zippy )" output'
      - run: strip output/zippy*
      - uses: actions/upload-artifact@v2
        with:
          path: output/zippy*
          name: zippy-${{ matrix.os }}-ghc-${{ matrix.ghc }}-${{ github.sha }}
      - run: cabal check
      - run: cabal sdist --output-dir output
      - if: matrix.os == 'ubuntu-18.04' && matrix.ghc == '8.10'
        uses: actions/upload-artifact@v2
        with:
          path: output/zippy-*.tar.gz
          name: zippy-${{ github.sha }}.tar.gz
